/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wael
 */
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.*;
import java.text.*;
import net.proteanit.sql.DbUtils;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


public class UserManage extends javax.swing.JFrame {

    static String access() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
    /**
     * Creates new form StudentManage
     */
    
    

    public UserManage() {
        initComponents();
        conn = JavaConnect.Connectrb();
        Update_table();
        Fillcombo();
    }
    private void Update_table(){
    try {
        String sql = "select Username,Password,HandPhone_Number,Age,CheckIn_Date,Division,BlackList,Gender,Name,IC_No,Nationality,Email,Emergency_Contact,Residence_Address from StudentInfo order by CheckIn_Date";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        Table_Student.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }finally {
         try{
           rs.close(); 
           pst.close(); 
         }catch(Exception e) { 
            }
        }
    }
    
    
    
    
    
    private void Fillcombo(){
        try{
            String sql = "select * from StudentInfo ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String name = rs.getString("Username");
                jComboBox1.addItem(name);
            }
            
         }catch(Exception e) {
             JOptionPane.showMessageDialog(null, e);
         }finally {
         try{
           rs.close(); 
           pst.close(); 
         }catch(Exception e) { 
            }
        }
            
      

    }
    
    
    public void Date123(){
        
        
    try{
        LocalDate today = LocalDate.now();
        System.out.println("Current date: " + today);

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");    //try to convert string format into date format
        String checkoutdate = dateFormat.format(txt_date.getDate());
        
        System.out.println(checkoutdate);
        LocalDate date2 = LocalDate.parse(checkoutdate); //try to convert date format into localdate format
        System.out.println("Checkout date: " + date2);
           
        long dateDifference = ChronoUnit.DAYS.between(date2,today);
        System.out.println("Days : "+dateDifference);
        
        if(dateDifference < 0){
            txt_blacklist.setText("No");
        }else if(dateDifference >=0){
            txt_blacklist.setText("Yes");
        }else{
            txt_blacklist.setText("");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "A gentle reminder: date input is recommened :-)");
        return;
    }
    }
    
    public void close(){

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    
    public void insertImage(Connection conn,String img,String strItemNum){
        
    }
    
    
   String accesss(){
       System.out.println(txt_username.getText());
       return txt_username.getText();
   }

   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cmd_clear = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_age = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_hpnumber = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_date = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_blacklist = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        Name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_icno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_nationality = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_emergencycontact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        txt_search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Student = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Button", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        cmd_clear.setText("Clear");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        cmd_update.setText("Update");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmd_delete.setText("Delete");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_save.setText("Save");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        jButton3.setText("Payment Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmd_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_update, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_clear)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resident Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        txt_age.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_ageCaretUpdate(evt);
            }
        });
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        txt_hpnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hpnumberActionPerformed(evt);
            }
        });

        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel3.setText("HP Number:");

        jLabel4.setText("Age:");

        jLabel6.setText("Due Date:");

        txt_date.setDateFormatString("yyyy-MM-dd");
        txt_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_dateKeyReleased(evt);
            }
        });

        jLabel7.setText("Division:");

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resident", "Admin" }));
        txt_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_comboActionPerformed(evt);
            }
        });

        jLabel8.setText("In Blacklist:");

        txt_blacklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_blacklistActionPerformed(evt);
            }
        });

        jLabel9.setText("Gender:");

        buttonGroup1.add(r_male);
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(r_female);
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });

        Name.setText("Name:");

        jLabel10.setText("IC_No:");

        txt_icno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_icnoActionPerformed(evt);
            }
        });

        jLabel11.setText("Nationality:");

        jLabel12.setText("Email:");

        jLabel13.setText("Emergency Contact:");

        jLabel14.setText("Residential Address:");

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane2.setViewportView(txt_address);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Name))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txt_username)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_hpnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(r_male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(r_female, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_password))))))
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_emergencycontact, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_blacklist, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(txt_icno)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(31, 31, 31)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nationality)
                                .addComponent(txt_email))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_blacklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_icno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r_female)
                            .addComponent(r_male)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hpnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txt_emergencycontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel14))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel5.setText("Search:");

        Table_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Student.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Table_StudentMouseMoved(evt);
            }
        });
        Table_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_StudentMouseClicked(evt);
            }
        });
        Table_Student.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_StudentKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_StudentKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Student);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(570, 570, 570))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(113, 113, 113)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_hpnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hpnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hpnumberActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try{
            String tmp = (String)jComboBox1.getSelectedItem();
            String sql = "select * from StudentInfo where Username=?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, tmp);
                    rs=pst.executeQuery();
                    if(rs.next()){
                        String add1 = rs.getString("Username");
                        txt_username.setText(add1);
                        String add2 = rs.getString("Password");
                        txt_password.setText(add2);
                        String add3 = rs.getString("HandPhone_Number");
                        txt_hpnumber.setText(add3);
                        String add4 = rs.getString("Age");
                        txt_age.setText(add4);
                        String add5 = rs.getString("CheckIn_Date");
                        ((JTextField)txt_date.getDateEditor().getUiComponent()).setText(add5);
                        String add6 = rs.getString("BlackList");
                    txt_blacklist.setText(add6);
                    GetValue.blacklist = add6;
                    
                    String add7 = rs.getString("Payment_Record");
                GetValue.description = add7;

                String add8=rs.getString("Gender");//Gender is the Column form Employeeinfo table
                switch (add8) {
                    case "Male":
                        r_male.setSelected(true);
                        break;
                    case "Female":
                        r_female.setSelected(true);
                        break;
                }
                
                String add9=rs.getString("Name");
                txt_name.setText(add9);
                
                String add10 = rs.getString("IC_No");
                txt_icno.setText(add10);
                
                String add11 = rs.getString("Nationality");
                txt_nationality.setText(add11);
                
                String add12 = rs.getString("Email");
                txt_email.setText(add12);
                
                String add13 = rs.getString("Emergency_Contact");
                txt_emergencycontact.setText(add13);
                
                String add14 = rs.getString("Residence_Address");
                txt_address.setText(add14);
                    }
                    
         }catch(Exception e) {
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
        try{
           String sql = "INSERT INTO StudentInfo (Username,Password,HandPhone_Number,Age,CheckIn_Date,Division,BlackList,Gender,Name,IC_No,Nationality,Email,Emergency_Contact,Residence_Address) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
           
           pst = conn.prepareStatement(sql);
           try {
                Integer.parseInt(txt_username.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "ID should be integer!");
                return;
            }
           if(!txt_name.getText().matches("^[a-zA-Z]+$")){
               JOptionPane.showMessageDialog(null, "Name should be in text only!");
               return;
           }
           try {
                Integer.parseInt(txt_hpnumber.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "hpnumber should be integer!");
                return;
            }
           
           try {
                Integer.parseInt(txt_age.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Age should be in number only!");
                return;
            }
           
           if(!txt_nationality.getText().matches("^[a-zA-Z]+$")){
               JOptionPane.showMessageDialog(null, "Nationality should be in text only!");
               return;
           }
           
           try {
                Integer.parseInt(txt_emergencycontact.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Emergency contact should be in number only!");
                return;
            }
           
           pst.setString(1, txt_username.getText());
           pst.setString(2, txt_password.getText());
           pst.setString(3, txt_hpnumber.getText());
           pst.setString(4, txt_age.getText());
           
           pst.setString(5, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           String value = txt_combo.getSelectedItem().toString();
           pst.setString(6, value);
           pst.setString(7, txt_blacklist.getText());
           //pst.setString(8, Gender);
            if (r_male.isSelected()== true){
                pst.setString(8, r_male.getText());
            }else{
                pst.setString(8, r_female.getText());
            }
           pst.setString(9, txt_name.getText());
           pst.setString(10,txt_icno.getText());
           pst.setString(11,txt_nationality.getText());
           pst.setString(12,txt_email.getText());
           pst.setString(13,txt_emergencycontact.getText());
           pst.setString(14,txt_address.getText());
          
           
           /*DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
           Date date = new Date();
           
           String currentdate = dateFormat.format(date);
           String checkoutdate = dateFormat.format(txt_date.getDate());
           
           System.out.println(currentdate);
           System.out.println(checkoutdate);*/
          
        Date123();
       
   
           
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Saved");
           Update_table();
           
           }
                    
         catch(Exception e) {
             JOptionPane.showMessageDialog(null, "This is student or admin has already exist!");
         }
        
        
        
    }//GEN-LAST:event_cmd_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        AdminInterface s = new AdminInterface();
        s.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:
        
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        
       if(p==0){ 
        String sql ="delete from StudentInfo where Username = ?";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_username.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
            Update_table();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        // TODO add your handling code here:
        try{
            try {
                Integer.parseInt(txt_username.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "ID should be integer!");
                return;
            }
            try {
                Integer.parseInt(txt_hpnumber.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "ID should be integer!");
                return;
            }
            try {
                Integer.parseInt(txt_age.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "ID should be integer!");
                return;
            }
            if(!txt_name.getText().matches("^[a-zA-Z]+$")){
               JOptionPane.showMessageDialog(null, "Name should be in text only!");
               return;
           }
            
            if(!txt_nationality.getText().matches("^[a-zA-Z]+$")){
               JOptionPane.showMessageDialog(null, "Nationality should be in text only!");
               return;
           }
           
           try {
                Integer.parseInt(txt_emergencycontact.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Emergency contact should be in number only!");
                return;
            }
           
            String value1 = txt_username.getText();
            String value2 = txt_password.getText();
            String value3 = txt_hpnumber.getText();
            String value4 = txt_age.getText();
            String value5 = ((JTextField)txt_date.getDateEditor().getUiComponent()).getText();
            String value6 = txt_combo.getSelectedItem().toString();
            
            Date123();
            
            String value7 = txt_blacklist.getText();
            String value8;
            if (r_male.isSelected()== true){
                value8 = "Male";
            }else{
                value8 = "Female";
            }
            
            String value9 = txt_name.getText();
            
            String value10 = txt_icno.getText();
            String value11 = txt_nationality.getText();
            String value12 = txt_email.getText();
            String value13 = txt_emergencycontact.getText();
            String value14 = txt_address.getText();
            
            //((JTextField)txt_date.getDateEditor().getUiComponent()).setText(add5);
            
            //String sql = "update StudentInfo set Username = '"+value1+"',Password = '"+value2+"', HandPhone_Number = '"+value3+"',Age='"+value4+"',CheckIn_Date='"+value5+"',Division='"+value6+"',BlackList='"+value7+"',Gender='"+value8+"',Name='"+value9+"' where Username = '"+value1+"'";
            String sql = "update StudentInfo set Username = '"+value1+"',Password = '"+value2+"', HandPhone_Number = '"+value3+"',Age='"+value4+"',CheckIn_Date='"+value5+"',Division='"+value6+"',BlackList='"+value7+"',Gender='"+value8+"',Name='"+value9+"',IC_No='"+value10+"',Nationality='"+value11+"',Email='"+value12+"',Emergency_Contact='"+value13+"',Residence_Address='"+value14+"' where Username = '"+value1+"'";
            
            pst = conn.prepareStatement(sql);
            pst.execute();
           
            
                    
            JOptionPane.showMessageDialog(null, "Updtaed");
            Update_table();
             
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
        // TODO add your handling code here:
        txt_username.setText("");
        txt_password.setText("");
        txt_hpnumber.setText("");
        txt_age.setText("");
        ((JTextField)txt_date.getDateEditor().getUiComponent()).setText("");
        txt_blacklist.setText("");
        txt_name.setText("");
        txt_icno.setText("");
        txt_nationality.setText("");
        txt_email.setText("");
        txt_emergencycontact.setText("");
        txt_address.setText("");
        
        
    }//GEN-LAST:event_cmd_clearActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try{
          String sql = "select * from StudentInfo where Username=? ";
          pst = conn.prepareStatement(sql);
          pst.setString(1, txt_search.getText());
          
          rs = pst.executeQuery();
          if(rs.next()){
              String add1 = rs.getString("Username");
              txt_username.setText(add1);
              String add2 = rs.getString("Password");
              txt_password.setText(add2);
              String add3 = rs.getString("HandPhone_Number");
              txt_hpnumber.setText(add3);
              String add4 = rs.getString("Age");
              txt_age.setText(add4);
              String add5 = rs.getString("CheckIn_Date");
                    ((JTextField)txt_date.getDateEditor().getUiComponent()).setText(add5);
                    GetValue.date = add5;
              String add6 = rs.getString("BlackList");
                    txt_blacklist.setText(add6);
                    GetValue.blacklist = add6;
                    
                    String add7 = rs.getString("Payment_Record");
                GetValue.description = add7;

                String add8=rs.getString("Gender");//Gender is the Column form Employeeinfo table
                switch (add8) {
                    case "Male":
                        r_male.setSelected(true);
                        break;
                    case "Female":
                        r_female.setSelected(true);
                        break;
                }
                
                String add9=rs.getString("Name");
                txt_name.setText(add9);
                
                String add10 = rs.getString("IC_No");
                txt_icno.setText(add10);
                
                String add11 = rs.getString("Nationality");
                txt_nationality.setText(add11);
                
                String add12 = rs.getString("Email");
                txt_email.setText(add12);
                
                String add13 = rs.getString("Emergency_Contact");
                txt_emergencycontact.setText(add13);
                
                String add14 = rs.getString("Residence_Address");
                txt_address.setText(add14);
          }
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally {
         try{
           rs.close(); 
           pst.close(); 
         }catch(Exception e) { 
            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dateKeyReleased
        // TODO add your handling code here:
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        System.out.println(dateFormat.format(txt_date.getDate()));
        
    }//GEN-LAST:event_txt_dateKeyReleased

    private void txt_blacklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_blacklistActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txt_blacklistActionPerformed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_ageCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_ageCaretUpdate
        // TODO add your handling code here:
        /*IntegerStringConverter isc=new IntegerStringConverter();
        int a=isc.fromString(txt_age.getText()); 
        if (a >20){
            String ab = "Yes";
            txt_blacklist.setText(ab);
        }else{
            String ab= "No";
            txt_blacklist.setText(ab);
        }*/
    }//GEN-LAST:event_txt_ageCaretUpdate

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PaymentInfo s = new PaymentInfo();
        s.setVisible(true);
        System.out.println(txt_username.getText());
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Table_StudentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_StudentKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){
            try{
                int row = Table_Student.getSelectedRow();
                String Table_Click = (Table_Student.getModel().getValueAt(row, 0).toString());
                String sql = "select * from StudentInfo where Username= '"+ Table_Click +"' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if(rs.next()){
                    String add1 = rs.getString("Username");
                    txt_username.setText(add1);
                    String add2 = rs.getString("Password");
                    txt_password.setText(add2);
                    String add3 = rs.getString("HandPhone_Number");
                    txt_hpnumber.setText(add3);
                    String add4 = rs.getString("Age");
                    txt_age.setText(add4);
                    String add5 = rs.getString("CheckIn_Date");
                    ((JTextField)txt_date.getDateEditor().getUiComponent()).setText(add5);
                    GetValue.date = add5;
                    String add6 = rs.getString("BlackList");
                    txt_blacklist.setText(add6);
                    GetValue.blacklist = add6;
                    
                    String add7 = rs.getString("Payment_Record");
                GetValue.description = add7;

                String add8=rs.getString("Gender");//Gender is the Column form Employeeinfo table
                switch (add8) {
                    case "Male":
                        r_male.setSelected(true);
                        break;
                    case "Female":
                        r_female.setSelected(true);
                        break;
                }
                
                String add9=rs.getString("Name");
                txt_name.setText(add9);
                
                String add10 = rs.getString("IC_No");
                txt_icno.setText(add10);
                
                String add11 = rs.getString("Nationality");
                txt_nationality.setText(add11);
                
                String add12 = rs.getString("Email");
                txt_email.setText(add12);
                
                String add13 = rs.getString("Emergency_Contact");
                txt_emergencycontact.setText(add13);
                
                String add14 = rs.getString("Residence_Address");
                txt_address.setText(add14);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e) {
                }
            }
        }
    }//GEN-LAST:event_Table_StudentKeyReleased

    private void Table_StudentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_StudentKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Table_StudentKeyPressed

    private void Table_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_StudentMouseClicked
        // TODO add your handling code here:
        try{
            int row = Table_Student.getSelectedRow();
            String Table_Click = (Table_Student.getModel().getValueAt(row, 0).toString());
            String sql = "select * from StudentInfo where Username= '"+ Table_Click +"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("Username");
                txt_username.setText(add1);
                GetValue.stuname = add1;
                String add2 = rs.getString("Password");
                txt_password.setText(add2);
                GetValue.password = add2;
                String add3 = rs.getString("HandPhone_Number");
                txt_hpnumber.setText(add3);
                GetValue.hpnum = add3;
                String add4 = rs.getString("Age");
                txt_age.setText(add4);
                GetValue.age = add4;
                String add5 = rs.getString("CheckIn_Date");
                ((JTextField)txt_date.getDateEditor().getUiComponent()).setText(add5);
                String add6 = rs.getString("BlackList");
                txt_blacklist.setText(add6);
                //pst.setString(5, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
                String add7 = rs.getString("Payment_Record");
                GetValue.description = add7;

                String add8=rs.getString("Gender");//Gender is the Column form Employeeinfo table
                switch (add8) {
                    case "Male":
                        r_male.setSelected(true);
                        break;
                    case "Female":
                        r_female.setSelected(true);
                        break;
                }
                
                String add9=rs.getString("Name");
                txt_name.setText(add9);
                
                String add10 = rs.getString("IC_No");
                txt_icno.setText(add10);
                
                String add11 = rs.getString("Nationality");
                txt_nationality.setText(add11);
                
                String add12 = rs.getString("Email");
                txt_email.setText(add12);
                
                String add13 = rs.getString("Emergency_Contact");
                txt_emergencycontact.setText(add13);
                
                String add14 = rs.getString("Residence_Address");
                txt_address.setText(add14);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally {
            try{
                rs.close();
                pst.close();
            }catch(Exception e) {
            }
        }
    }//GEN-LAST:event_Table_StudentMouseClicked

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "you select" + txt_username.getText());
    }//GEN-LAST:event_txt_usernameMouseClicked

    private void Table_StudentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_StudentMouseMoved
      
    }//GEN-LAST:event_Table_StudentMouseMoved

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_comboActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        Gender = "Male";
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
        Gender = "Female";
    }//GEN-LAST:event_r_femaleActionPerformed

    private void txt_icnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_icnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_icnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JTable Table_Student;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton cmd_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_blacklist;
    private javax.swing.JComboBox<String> txt_combo;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emergencycontact;
    private javax.swing.JTextField txt_hpnumber;
    private javax.swing.JTextField txt_icno;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nationality;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private String Gender;
    
    
    
}
